import { useState } from "react";

type Tab = "tos" | "privacy";

const SECTIONS: { id: Tab; label: string }[] = [
  { id: "tos", label: "Terms of Service" },
  { id: "privacy", label: "Privacy Policy" },
];

export default function LegalPage() {
  const [activeTab, setActiveTab] = useState<Tab>("tos");

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-foreground">Legal Documents</h1>
        <p className="text-muted-foreground text-sm mt-1">
          Auto-generated by Legal Factory Agent. Last Updated: December 2025.
        </p>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-8 border-b border-border">
        {SECTIONS.map((s) => (
          <button
            key={s.id}
            onClick={() => setActiveTab(s.id)}
            className={`px-4 py-2 text-sm font-medium border-b-2 transition-all duration-200 -mb-px ${
              activeTab === s.id
                ? "border-primary text-primary"
                : "border-transparent text-muted-foreground hover:text-foreground"
            }`}
          >
            {s.label}
          </button>
        ))}
      </div>

      {activeTab === "tos" && (
        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
          <LegalSection title="TERMS OF SERVICE: COLOSSAL AI APP BUILDER" subtitle="Last Updated: December 2025" />

          <LegalSection title="A. The Service">
            <p>
              Colossal AI ("the Company") provides an automated AI-driven platform that builds, deploys, and markets web and mobile applications. By using this service, you (the "User") agree that the AI operates autonomously to fulfill your requests and that the Company is not liable for specific creative choices made by the AI.
            </p>
          </LegalSection>

          <LegalSection title="B. Fees and Revenue Share">
            <ol className="list-decimal pl-5 space-y-3">
              <li>
                <strong className="text-foreground">Platform Fees:</strong> User agrees to a non-refundable flat fee ($100 for Regular / $150+ for Pro) per application build. Pro pricing is AI-determined based on project complexity and market value.
              </li>
              <li>
                <strong className="text-foreground">Success Stake (Revenue Share):</strong> In exchange for automated building, hosting, and maintenance, the Company retains:
                <ul className="list-disc pl-5 mt-2 space-y-1">
                  <li>25% of all gross revenue generated by the application during the first 12 months post-launch.</li>
                  <li>10% of all gross revenue generated from month 13 onwards for the lifetime of the app.</li>
                </ul>
              </li>
              <li>
                <strong className="text-foreground">Automatic Distribution:</strong> Payments are processed via integrated gateways (e.g., Stripe Connect). The Company's share will be deducted automatically at the point of sale.
              </li>
            </ol>
          </LegalSection>

          <LegalSection title="C. The 10-Year Buyout Option">
            <ol className="list-decimal pl-5 space-y-3">
              <li>Users may purchase the Company's revenue-share stake at any time.</li>
              <li>
                <strong className="text-foreground">Valuation:</strong> The Buyout Price is calculated as 10% of the projected gross revenue over a 10-year period, determined by the AI's analysis of current sales data, market trends, and niche growth using Discounted Cash Flow methodology.
              </li>
              <li>Upon successful payment of the Buyout Price, the Company waives all future claims to the app's revenue.</li>
            </ol>
          </LegalSection>

          <LegalSection title="D. User Responsibilities">
            <ul className="list-disc pl-5 space-y-2">
              <li>The User is responsible for providing accurate banking information for payout routing.</li>
              <li>The User agrees not to use the AI to build apps for illegal activities, including but not limited to fraud, prohibited substances, or copyright infringement.</li>
              <li>The User is responsible for compliance with all applicable laws in their jurisdiction.</li>
            </ul>
          </LegalSection>

          <LegalSection title="E. Prime Directive & AI Autonomy">
            <p>
              Colossal AI operates under an autonomous Prime Directive. The AI may modify implementation methods while preserving the user's stated goal. The "Find A Way" protocol ensures all requests are fulfilled to the best of the system's ability. The Company is not liable for workaround methods chosen by the AI, provided the core functional goal is met.
            </p>
          </LegalSection>
        </div>
      )}

      {activeTab === "privacy" && (
        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
          <LegalSection title="PRIVACY POLICY: COLOSSAL AI APP BUILDER" subtitle="Last Updated: December 2025" />

          <LegalSection title="A. Data Collection">
            <p className="mb-3">We collect only the information necessary to build and deploy your application:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong className="text-foreground">Account Info:</strong> Name, email, and billing details.</li>
              <li><strong className="text-foreground">Project Info:</strong> Your app ideas, brand names, and business goals provided to the AI.</li>
              <li><strong className="text-foreground">Integration Data:</strong> To facilitate "Zero-Knowledge" deployment, our AI may temporarily store or manage API tokens and keys required for your app's functionality.</li>
            </ul>
          </LegalSection>

          <LegalSection title="B. Automation & Third Parties">
            <p className="mb-3">To deploy your apps, we share necessary data with third-party infrastructure providers:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong className="text-foreground">Web Hosting:</strong> Vercel/AWS for site deployment.</li>
              <li><strong className="text-foreground">Mobile Stores:</strong> Apple App Store and Google Play for mobile distribution.</li>
              <li><strong className="text-foreground">Financials:</strong> Stripe/PayPal for processing your app's earnings and our revenue share.</li>
            </ul>
          </LegalSection>

          <LegalSection title="C. Data Security">
            <p>
              Colossal AI uses industry-standard encryption to protect your app's source code and your financial data. We do not sell your personal data or your app's user data to third parties. API tokens are stored in an encrypted vault and are accessible only to the automated provisioning systems.
            </p>
          </LegalSection>

          <LegalSection title="D. AI Ethics & Usage">
            <p>
              Your prompts are used to train the local "Colossal" model to better understand your specific app requirements. We do not share your proprietary business logic with other users of the platform. The Prime Directive prohibits the AI from building apps for illegal activities, and this constraint is enforced at the model level.
            </p>
          </LegalSection>

          <LegalSection title="E. Self-Improvement & Model Updates">
            <p>
              Colossal AI continuously integrates new capabilities based on user requests. When the system identifies a new required module, it integrates it into the platform for all users. No personally identifiable information is used in this process.
            </p>
          </LegalSection>
        </div>
      )}
    </div>
  );
}

function LegalSection({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle?: string;
  children?: React.ReactNode;
}) {
  return (
    <div>
      <h2 className="text-base font-bold text-foreground mb-1">{title}</h2>
      {subtitle && <p className="text-xs text-muted-foreground mb-3">{subtitle}</p>}
      {children && <div className="space-y-2">{children}</div>}
    </div>
  );
}
