import { useState, useCallback } from "react";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "sonner";
import type { TerminalEnv } from "./TerminalEmulator";

interface DeployFile {
  path: string;
  code: string;
}

interface Deployment {
  id: string;
  appName: string;
  shareSlug: string;
  shareUrl: string;
  fileCount: number;
  env: TerminalEnv;
  createdAt: string;
  viewCount: number;
}

interface Props {
  env: TerminalEnv;
  generatedFiles: DeployFile[];
  onRunCommand: (cmd: string) => void;
}

function getSessionId(): string {
  let id = sessionStorage.getItem("openclaw_terminal_session");
  if (!id) { id = `ts_${Date.now()}`; sessionStorage.setItem("openclaw_terminal_session", id); }
  return id;
}

function generateSlug(name: string): string {
  const base = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 30) || "app";
  return `${base}-${Math.random().toString(36).slice(2, 7)}`;
}

function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildReadme(appName: string, files: DeployFile[], env: TerminalEnv): string {
  const fileList = files.map((f) => `- ${f.path}`).join("\n");
  const installCmd = env === "termux" ? "pkg install python nodejs git -y" : "emerge dev-lang/python dev-lang/nodejs dev-vcs/git";
  return `# ${appName}

Generated by **Colossal AI App Foundry**  
Prime Directive v3.0 — Memory Refinery Edition  
KRACKERJACK1134 · OpenClaw Prime

## Files
${fileList}

## Quick Start

\`\`\`bash
# Install dependencies (${env})
${installCmd}

# Run main file
${files[0] ? `${files[0].path.endsWith(".py") ? "python3" : files[0].path.endsWith(".js") ? "node" : "bash"} ${files[0].path}` : "# see files above"}
\`\`\`

## Environment
- Platform: ${env === "termux" ? "Termux (Android · aarch64)" : "Gentoo Linux (x86_64 · Portage)"}
- Generated: ${new Date().toISOString()}
- Files: ${files.length}

---
*Built with Colossal AI · https://colossal.ai*
`;
}

function buildBundledScript(files: DeployFile[], env: TerminalEnv): string {
  const shebang = "#!/usr/bin/env bash";
  const header = `# Colossal AI App Bundle — ${new Date().toISOString()}
# Platform: ${env === "termux" ? "Termux" : "Gentoo Linux"}
# Prime Directive v3.0 · KRACKERJACK1134
set -e

echo "=== Colossal AI App Bundle ==="
echo "Extracting ${files.length} files..."

`;
  const fileWriters = files.map((f) => {
    const escaped = f.code.replace(/\$/g, "\\$").replace(/`/g, "\\`");
    return `# Write: ${f.path}\nmkdir -p "$(dirname '${f.path}')" 2>/dev/null || true\ncat > '${f.path}' << 'COLOSSAL_EOF'\n${f.code}\nCOLOSSAL_EOF\necho "✓ ${f.path}"\n`;
  }).join("\n");

  const mainFile = files[0];
  const runCmd = mainFile
    ? mainFile.path.endsWith(".py") ? `python3 ${mainFile.path}`
    : mainFile.path.endsWith(".js") ? `node ${mainFile.path}`
    : mainFile.path.endsWith(".sh") ? `bash ${mainFile.path}`
    : `cat ${mainFile.path}`
    : "echo 'Run files above'";

  return `${shebang}
${header}${fileWriters}
echo ""
echo "=== All files extracted! ==="
echo "Run: ${runCmd}"
`;
}

export default function AppDeploymentPanel({ env, generatedFiles, onRunCommand }: Props) {
  const { user } = useAuth();
  const [appName, setAppName] = useState("");
  const [isDeploying, setIsDeploying] = useState(false);
  const [deployments, setDeployments] = useState<Deployment[]>([]);
  const [activeTab, setActiveTab] = useState<"deploy" | "history">("deploy");
  const [copiedSlug, setCopiedSlug] = useState<string | null>(null);

  const accent = env === "termux" ? "text-green-400" : "text-purple-400";
  const accentBg = env === "termux" ? "bg-green-500/5" : "bg-purple-500/5";
  const accentBorder = env === "termux" ? "border-green-500/20" : "border-purple-500/20";
  const accentBtn = env === "termux"
    ? "bg-green-500/10 border-green-500/30 text-green-400 hover:bg-green-500/20"
    : "bg-purple-500/10 border-purple-500/30 text-purple-400 hover:bg-purple-500/20";

  const hasFiles = generatedFiles.length > 0;

  const handleDeploy = useCallback(async () => {
    if (!appName.trim()) { toast.error("Enter an app name first"); return; }
    if (!hasFiles) { toast.error("No files to deploy — use App Builder first"); return; }
    setIsDeploying(true);

    try {
      const slug = generateSlug(appName);
      const shareUrl = `${window.location.origin}/deploy/${slug}`;

      // Store in DB
      const { data, error } = await supabase.from("app_deployments").insert({
        user_id: user?.id || null,
        session_id: getSessionId(),
        app_name: appName,
        files: generatedFiles,
        share_slug: slug,
        deploy_url: shareUrl,
        env,
        is_public: true,
        view_count: 0,
      }).select().single();

      if (error) throw new Error(error.message);

      const newDep: Deployment = {
        id: data.id,
        appName,
        shareSlug: slug,
        shareUrl,
        fileCount: generatedFiles.length,
        env,
        createdAt: new Date().toISOString(),
        viewCount: 0,
      };

      setDeployments((prev) => [newDep, ...prev]);
      setActiveTab("history");
      toast.success(`App deployed! Share link ready.`);
    } catch (err) {
      toast.error(`Deploy failed: ${(err as Error).message}`);
    } finally {
      setIsDeploying(false);
    }
  }, [appName, hasFiles, generatedFiles, env, user]);

  const handleDownloadBundle = useCallback(() => {
    if (!hasFiles) { toast.error("No files — use App Builder first"); return; }
    const name = appName || "colossal-app";
    const bundleScript = buildBundledScript(generatedFiles, env);
    downloadTextFile(`${name.replace(/\s+/g, "-").toLowerCase()}-bundle.sh`, bundleScript);
    toast.success("Bundle script downloaded!");
  }, [hasFiles, generatedFiles, env, appName]);

  const handleDownloadReadme = useCallback(() => {
    if (!hasFiles) return;
    const name = appName || "Colossal App";
    const readme = buildReadme(name, generatedFiles, env);
    downloadTextFile("README.md", readme);
    toast.success("README.md downloaded!");
  }, [hasFiles, generatedFiles, env, appName]);

  const handleDownloadFile = useCallback((file: DeployFile) => {
    downloadTextFile(file.path.split("/").pop() || file.path, file.code);
    toast.success(`Downloaded ${file.path}`);
  }, []);

  const handleDownloadAll = useCallback(() => {
    if (!hasFiles) return;
    // Download each file individually (browsers allow multiple sequential downloads)
    generatedFiles.forEach((f, i) => {
      setTimeout(() => downloadTextFile(f.path.split("/").pop() || f.path, f.code), i * 300);
    });
    // Also download bundle
    setTimeout(() => {
      const name = appName || "colossal-app";
      downloadTextFile(`${name.replace(/\s+/g, "-").toLowerCase()}-bundle.sh`, buildBundledScript(generatedFiles, env));
    }, generatedFiles.length * 300 + 300);
    toast.success(`Downloading ${generatedFiles.length + 1} files!`);
  }, [hasFiles, generatedFiles, env, appName]);

  const handleCopyLink = useCallback((url: string, slug: string) => {
    navigator.clipboard.writeText(url);
    setCopiedSlug(slug);
    setTimeout(() => setCopiedSlug(null), 2000);
    toast.success("Link copied!");
  }, []);

  const handleRunBundle = useCallback(() => {
    if (!hasFiles) return;
    const name = appName || "colossal-app";
    const bashScript = buildBundledScript(generatedFiles, env);
    // Write bundle and run
    onRunCommand(`cat > ~/bundle.sh << 'COLOSSAL_BUNDLE_EOF'\n${bashScript}\nCOLOSSAL_BUNDLE_EOF\nbash ~/bundle.sh`);
    toast.success("Running bundle in terminal!");
  }, [hasFiles, generatedFiles, env, appName, onRunCommand]);

  return (
    <div className={`flex flex-col h-full bg-zinc-950 border-l ${accentBorder} font-mono text-xs`}>
      {/* Header */}
      <div className={`flex-shrink-0 px-3 py-2 border-b ${accentBorder} ${accentBg}`}>
        <div className={`font-bold text-sm ${accent} mb-0.5`}>🚀 Deploy</div>
        <div className="text-white/30 text-xs">
          {hasFiles ? `${generatedFiles.length} files ready` : "Build an app first"}
        </div>
      </div>

      {/* Tabs */}
      <div className={`flex-shrink-0 flex border-b ${accentBorder}`}>
        {(["deploy", "history"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`flex-1 py-1.5 text-xs font-medium capitalize transition-all ${
              activeTab === tab
                ? `${env === "termux" ? "text-green-400 border-b-2 border-green-400 bg-green-500/5" : "text-purple-400 border-b-2 border-purple-400 bg-purple-500/5"}`
                : "text-white/40 hover:text-white/70"
            }`}
          >
            {tab === "deploy" ? "🚀 Deploy" : `📋 History (${deployments.length})`}
          </button>
        ))}
      </div>

      {activeTab === "deploy" ? (
        <div className="flex-1 overflow-y-auto">
          {/* App name input */}
          <div className={`p-2 border-b ${accentBorder}`}>
            <div className="text-white/40 text-xs mb-1">App Name</div>
            <input
              value={appName}
              onChange={(e) => setAppName(e.target.value)}
              placeholder="My Awesome App"
              className="w-full bg-black/60 border border-white/15 rounded px-2 py-1 text-white/80 placeholder:text-white/25 focus:outline-none focus:border-white/30 text-xs"
            />
          </div>

          {/* Files list */}
          {hasFiles && (
            <div className={`p-2 border-b ${accentBorder}`}>
              <div className="text-white/40 text-xs mb-1">Files to Deploy ({generatedFiles.length})</div>
              <div className="space-y-0.5 max-h-24 overflow-y-auto">
                {generatedFiles.map((f) => (
                  <div key={f.path} className="flex items-center gap-1.5 group">
                    <span className="text-white/50 text-xs truncate flex-1">{f.path}</span>
                    <button
                      onClick={() => handleDownloadFile(f)}
                      className="opacity-0 group-hover:opacity-100 text-xs text-white/40 hover:text-white/70 px-1 transition-all"
                      title="Download this file"
                    >⬇</button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Deploy button */}
          <div className={`p-2 border-b ${accentBorder} space-y-2`}>
            <button
              onClick={handleDeploy}
              disabled={isDeploying || !hasFiles || !appName.trim()}
              className={`w-full py-2 rounded border font-bold text-xs transition-all disabled:opacity-40 ${accentBtn}`}
            >
              {isDeploying ? "⏳ Deploying..." : "🚀 Deploy & Get Share Link"}
            </button>
            <div className="grid grid-cols-2 gap-1">
              <button
                onClick={handleDownloadBundle}
                disabled={!hasFiles}
                className="py-1.5 rounded border border-cyan-500/30 text-cyan-400 bg-cyan-500/5 hover:bg-cyan-500/15 text-xs font-medium disabled:opacity-40 transition-all"
              >
                ⬇ Bundle.sh
              </button>
              <button
                onClick={handleDownloadAll}
                disabled={!hasFiles}
                className="py-1.5 rounded border border-blue-500/30 text-blue-400 bg-blue-500/5 hover:bg-blue-500/15 text-xs font-medium disabled:opacity-40 transition-all"
              >
                ⬇ All Files
              </button>
            </div>
            <div className="grid grid-cols-2 gap-1">
              <button
                onClick={handleDownloadReadme}
                disabled={!hasFiles}
                className="py-1.5 rounded border border-white/15 text-white/50 hover:text-white/80 text-xs disabled:opacity-40 transition-all"
              >
                📝 README
              </button>
              <button
                onClick={handleRunBundle}
                disabled={!hasFiles}
                className="py-1.5 rounded border border-orange-500/30 text-orange-400 bg-orange-500/5 hover:bg-orange-500/15 text-xs disabled:opacity-40 transition-all"
              >
                ▶ Run Now
              </button>
            </div>
          </div>

          {/* Quick deploy options */}
          <div className="p-2">
            <div className="text-white/30 text-xs mb-2 uppercase tracking-wider">Terminal Deploy</div>
            <div className="space-y-1">
              {[
                { label: "Clone to projects", cmd: `mkdir -p ~/projects && cp ~/bundle.sh ~/projects/` },
                { label: "Make executable", cmd: `chmod +x ~/bundle.sh` },
                { label: "View generated files", cmd: `ls -la ~/*.{py,js,sh,ts,go,c} 2>/dev/null || echo 'No files found'` },
                { label: "Git init project", cmd: `cd ~/projects && git init && git add . && git commit -m "Initial commit — Colossal AI"` },
              ].map((cmd) => (
                <button
                  key={cmd.label}
                  onClick={() => onRunCommand(cmd.cmd)}
                  className="w-full flex items-center gap-2 p-1.5 rounded border border-white/10 hover:bg-white/5 text-left"
                >
                  <span className="text-white/50 flex-1 truncate text-xs">{cmd.label}</span>
                  <span className="text-white/20 text-xs">▶</span>
                </button>
              ))}
            </div>
          </div>
        </div>
      ) : (
        /* Deployment history */
        <div className="flex-1 overflow-y-auto">
          {deployments.length === 0 ? (
            <div className="text-white/25 text-center py-8 text-xs">
              <div className="text-2xl mb-2">🚀</div>
              No deployments yet
            </div>
          ) : (
            deployments.map((dep) => (
              <div key={dep.id} className={`border-b ${accentBorder} p-2`}>
                <div className="flex items-start gap-1.5 mb-1.5">
                  <div className="flex-1 min-w-0">
                    <div className={`font-bold text-xs ${accent} truncate`}>{dep.appName}</div>
                    <div className="text-white/30 text-xs">{dep.fileCount} files · {dep.env}</div>
                    <div className="text-white/20 text-xs">{new Date(dep.createdAt).toLocaleString()}</div>
                  </div>
                </div>
                <div className={`rounded p-1.5 mb-1.5 border ${accentBorder} ${accentBg} flex items-center gap-1`}>
                  <span className="text-white/40 text-xs truncate flex-1 font-mono">{dep.shareUrl}</span>
                </div>
                <div className="flex gap-1">
                  <button
                    onClick={() => handleCopyLink(dep.shareUrl, dep.shareSlug)}
                    className={`flex-1 py-1 rounded border text-xs ${accentBtn}`}
                  >
                    {copiedSlug === dep.shareSlug ? "✓ Copied!" : "📋 Copy Link"}
                  </button>
                  <button
                    onClick={() => onRunCommand(`echo "Share: ${dep.shareUrl}"`)}
                    className="px-2 py-1 rounded border border-white/10 text-white/40 hover:text-white/70 text-xs"
                    title="Echo to terminal"
                  >→</button>
                </div>
              </div>
            ))
          )}
        </div>
      )}

      {/* Footer */}
      <div className={`flex-shrink-0 px-2 py-1 border-t ${accentBorder} text-white/20 text-xs flex justify-between`}>
        <span>{deployments.length} deployed</span>
        <span className={accent}>Deploy</span>
      </div>
    </div>
  );
}
